    language: python # => 1
    python: # => 2
      - "3.6.1"
    #services: # => 3
    #  - mysql
    env: # => 4
      - DJANGO=1.11 #DB=mysql
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      #- mysql -e 'create database test;' -u root
      - python manage.py migrate
    script: # => 7
      - python manage.py test