# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='expected_end',
        ),
        migrations.AddField(
            model_name='loan',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='start',
            field=models.DateField(default=datetime.datetime(2016, 7, 21, 12, 46, 32, 256425, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
