# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20160721_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='interest',
            new_name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='interesttype',
            name='period',
        ),
        migrations.AddField(
            model_name='interesttype',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
