# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20160721_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
