# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20160721_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='interesttype',
            name='days',
        ),
        migrations.AddField(
            model_name='interesttype',
            name='type',
            field=models.CharField(choices=[('Simple', 'simple'), ('Compound', 'compound')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interesttype',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loans.Period'),
            preserve_default=False,
        ),
    ]
