# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20160721_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='compound',
            field=models.IntegerField(default=1, help_text='number of compounding periods'),
            preserve_default=False,
        ),
    ]
