# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 11:08
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shares', 'Share'), ('savings', 'Saving'), ('fine', 'Fine'), ('operations', 'Operation'), ('registration', 'Registration'), ('other', 'Other')], max_length=50)),
                ('source', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money')], max_length=50)),
                ('amount', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinesSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Fines',
                'proxy': True,
                'verbose_name_plural': 'Fines',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OperationsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Operations',
                'proxy': True,
                'verbose_name_plural': 'Operations',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SavingsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Savings',
                'proxy': True,
                'verbose_name_plural': 'Savings',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SharesSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Shares',
                'proxy': True,
                'verbose_name_plural': 'Shares',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ExpenseCategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
